---
title: "Pics"
author: "Shivam"
date: "April 10, 2019"
output: html_document
---

#Now creating lollipops for top ten variables for points from rf
```{r}
# Library
library(tidyverse)
 
# Create data
data=data.frame(x=c("completed_passes","t_creativity","t_minutes","bps_t","t_influence","ict_index_t","threat_t", "clean_sheets","clean_sheets_t","bonus_t"), y=c(100,98.0474,96.1142,93.82769,93.03703,91.40531,87.84151,86.36339,83.58515,81.12225))
```
```{r}
# 1 - Custom markers (left)
# note: shape = integer between 0 and 25
# note: stroke exists only for shapes between 1 and 24
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y)) +
  geom_point( size=5, color="red", fill=alpha("orange", 0.3), alpha=0.7, shape=21, stroke=2) 
 
# 2 - Custom stems (right)
# note: size is the width in mm
# note: style can be in: "blank", "solid", "dashed", "dotted", "dotdash", "longdash","twodash"
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y) , size=1, color="blue", linetype="dotted" ) +
  geom_point()

```

```{r}
#sth new
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y), color="grey") +
  geom_point( color="orange", size=4) +
  theme_light() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  xlab("") +
  ylab("Value of Y")
```
```{r}
# Horizontal 
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y), color="skyblue") +
  geom_point( color="blue", size=4, alpha=0.6) +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  ) 
```
```{r}
# Reorder
data %>%
  arrange(y) %>%
  mutate(x=factor(x,x)) %>%
  ggplot( aes(x=x, y=y)) +
    geom_segment( aes(x=x, xend=x, y=0, yend=y), color="skyblue", size=1) +
    geom_point( color="blue", size=4, alpha=0.6) +
    theme_light() +
    coord_flip() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.border = element_blank(),
      axis.ticks.y = element_blank()
    ) +
  xlab("") +
  ylab("Predictive Power of Predictors for Points")+theme(axis.text=element_text(size=16),
        axis.title=element_text(size=16))
```

#For Dream team
```{r}
# Create data
data=data.frame(x=c("t_influence","bonus_t","transfers_balance","ict_index_t","transfers_out","t_creativity","bonus","selected_by_percent","bps_t","threat_t"), y=c(100,93.7299,88.63,82.68,79.214,75.72,75.64,69.3,68.147,67.27))
```
```{r}
# 1 - Custom markers (left)
# note: shape = integer between 0 and 25
# note: stroke exists only for shapes between 1 and 24
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y)) +
  geom_point( size=5, color="red", fill=alpha("orange", 0.3), alpha=0.7, shape=21, stroke=2) 
 
# 2 - Custom stems (right)
# note: size is the width in mm
# note: style can be in: "blank", "solid", "dashed", "dotted", "dotdash", "longdash","twodash"
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y) , size=1, color="blue", linetype="dotted" ) +
  geom_point()

```

```{r}
#sth new
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y), color="grey") +
  geom_point( color="orange", size=4) +
  theme_light() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  xlab("") +
  ylab("Value of Y")
```
```{r}
# Horizontal 
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y), color="skyblue") +
  geom_point( color="blue", size=4, alpha=0.6) +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  ) 
```

```{r}
# Reorder
data %>%
  arrange(y) %>%
  mutate(x=factor(x,x)) %>%
  ggplot( aes(x=x, y=y)) +
    geom_segment( aes(x=x, xend=x, y=0, yend=y), color="skyblue", size=1) +
    geom_point( color="blue", size=4, alpha=0.6) +
    theme_light() +
    coord_flip() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.border = element_blank(),
      axis.ticks.y = element_blank()
    ) +
  xlab("") +
  ylab("Predictive Power of Factors for Dream Team")+theme(axis.text=element_text(size=16),
        axis.title=element_text(size=16))
```
#Two plots
```{r}
library(readxl)
P.train <- read_excel("C:/College of Wooster/Sophomore second semester/Math Model/Final Project/CombinedTraining.xlsx")
#Create data
a=P.train$completed_passes
b=P.train$F_pts
 
# I divide the screen in 2 line and 1 column only
my_screen_step1 <- split.screen(c(2, 1))
 
# I add one graph on the screen number 1 which is on top :
screen(my_screen_step1[1])
plot( a,b , pch=20 , xlab="Number of Completed Passes" ,ylab="Points Next GW", cex=2 , col=rgb(0.4,0.9,0.8,0.5) )
abline(lm(b ~ a), col="red", lty=1, lwd= 3)+theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))
 
 
# I divide the second screen in 2 columns :
my_screen_step2=split.screen(c(1, 2), screen = my_screen_step1[2])
screen(my_screen_step2[1])
hist(a, border=F , col=rgb(0.2,0.2,0.8,0.7) , main="" , xlab="Distribution of Completed Passes")
screen(my_screen_step2[2])
hist(b, border=F , col=rgb(0.8,0.2,0.8,0.7) , main="" ,  xlab="Distribution of Points Next GW")
```


#Dream team against influence
```{r}
par(mar = rep(2, 4))
#Create data
a=P.train$t_influence
b=P.train$dream_team
 
# I divide the screen in 2 line and 1 column only
my_screen_step1 <- split.screen(c(2, 1))
 
# I add one graph on the screen number 1 which is on top :
screen(my_screen_step1[1])
plot( a,b , pch=20 , xlab="Influence" ,ylab="Dream Team", cex=3 , col=rgb(0.4,0.9,0.8,0.5) )
abline(lm(b ~ a), col="red", lty=1, lwd= 3)
 
 
# I divide the second screen in 2 columns :
my_screen_step2=split.screen(c(1, 2), screen = my_screen_step1[2])
screen(my_screen_step2[1])
hist(a, border=F , col=rgb(0.2,0.2,0.8,0.7) , main="" , xlab="Distribution of Influence")
screen(my_screen_step2[2])
hist(b, border=F , col=rgb(0.8,0.2,0.8,0.7) , main="" ,  xlab="Distribution of Dream Team")+theme(axis.text=element_text(size=16),
        axis.title=element_text(size=16))
```
```{r}
#some stats on dream team against influence
linearMod <- lm(dream_team ~ t_influence, data=P.train)
summary(linearMod)
cor(P.train$t_influence, P.train$dream_team)
```

#For n vs N
```{r}
# Create data
data=data.frame(x=c(1,5,10,20,50), y=c(969, 410, 313, 262, 205))
```
```{r}
# 1 - Custom markers (left)
# note: shape = integer between 0 and 25
# note: stroke exists only for shapes between 1 and 24
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y)) +
  geom_point( size=5, color="skyblue", fill=alpha("blue", 0.3), alpha=0.7, shape=21, stroke=2) + labs(x = "f")+ labs(y = "Price per person in $")
 
# 2 - Custom stems (right)
# note: size is the width in mm
# note: style can be in: "blank", "solid", "dashed", "dotted", "dotdash", "longdash","twodash"
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y) , size=1, color="blue", linetype="dotted" ) +
  geom_point()

```
```{r}
# Horizontal 
ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y), color="skyblue") +
  geom_point( color="blue", size=4, alpha=0.6) +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  ) 
```

